FROM python:3.9
RUN apt-get update && apt-get install -y g++

WORKDIR /app
COPY Online_Compiler /app/compiler
COPY requirements.txt /app/
COPY Online_Judge /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE=Online_Judge.settings
ENV PYTHONUNBUFFERED=1

CMD [ "python","manage.py","runserver","0.0.0.0:8000" ]