# Generated by Django 5.0.6 on 2024-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
