# Generated by Django 5.0.6 on 2024-06-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
