# Generated by Django 5.0.6 on 2024-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_employee',
            name='employee_id',
            field=models.IntegerField(unique=True),
        ),
    ]
