# Generated by Django 5.0.6 on 2024-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_employee',
            name='employee_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
