# Generated by Django 5.0.6 on 2024-06-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_problem_input_test_problem_output_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='examples',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_constraints',
            field=models.TextField(blank=True, null=True),
        ),
    ]
