# Generated by Django 5.0.6 on 2024-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_problem_constraint_problem_output_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='output_const',
            field=models.TextField(blank=True, null=True),
        ),
    ]
