# Generated by Django 5.0.6 on 2024-06-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Compiler', '0002_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_input',
            name='test_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_input',
            name='test_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
