# Generated by Django 5.0.6 on 2024-06-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Compiler', '0002_submission_code'),
        ('Online_Compiler', '0003_user_input_test_input_user_input_test_output'),
    ]

    operations = [
    ]
