# Generated by Django 5.0.6 on 2024-06-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Compiler', '0004_merge_20240610_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='submission',
        ),
    ]
